services:
  - type: web
    name: doctasky-api
    env: docker
    dockerfilePath: ./infra/Dockerfile.api
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: APP_REDIS_URL
        sync: false
      - key: APP_STORAGE_ROOT
        value: /tmp/storage
      - key: APP_DELETE_AFTER_HOURS
        value: "24"
      - key: APP_CORS_ORIGINS
        value: "*"
      - key: APP_FOOTBALL_DATA_API_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
